name: 🐛 Bug Report
description: Report a bug or unexpected behavior in the Drone Dashboard
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us reproduce and fix the issue.
        
        **Note**: Each confirmed bug will be assigned an official Bug ID and logged in our [BUGS.md](../BUGS.md) documentation.

  - type: input
    id: bug-title
    attributes:
      label: Bug Title
      description: A concise, descriptive title for the bug
      placeholder: "Theme persistence not working across pages"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How severely does this bug impact functionality?
      options:
        - P0 (Critical) - System unusable, data loss, security issues
        - P1 (High) - Major functionality broken, poor user experience
        - P2 (Medium) - Minor functionality issues, cosmetic problems
        - P3 (Low) - Enhancement requests, nice-to-have fixes
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug
      value: |
        1. Navigate to...
        2. Click on...
        3. Observe that...
      render: markdown
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Provide details about your environment
      value: |
        - **Browser**: (e.g., Chrome 120, Safari 17, Firefox 121)
        - **Device**: (e.g., Desktop, iPhone 14, Samsung Galaxy S23)
        - **OS**: (e.g., macOS Sonoma, Windows 11, Ubuntu 22.04)
        - **Screen Resolution**: (e.g., 1920x1080, 375x812)
        - **Node.js Version**: (if applicable)
      render: markdown
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: Add screenshots, videos, or GIFs that help explain the problem
      placeholder: Drag and drop files here or paste image URLs...

  - type: textarea
    id: console-logs
    attributes:
      label: Console Logs/Error Messages
      description: Include any relevant console errors or log messages
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, workarounds, or related information
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported already
          required: true
        - label: I can reproduce this bug consistently
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I understand this bug will be assigned an official Bug ID and tracked in BUGS.md
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        **What happens next?**
        1. We'll review your bug report and assign it a priority
        2. If confirmed, it will receive an official Bug ID (format: `BUG-YYYYMMDD-###`)
        3. The bug will be logged in our [BUGS.md](../BUGS.md) documentation
        4. We'll update this issue with the Bug ID and tracking information
        
        Thank you for helping improve the Drone Dashboard! 🚁
